---@class LayoutAPI
---
---Keyboard layout switching API:
---an interface providing getting and setting current keyboard layout.
---
---Layout API is agnostic of the underlying implementation,
---which actually handles layout switching. Supported implementations
---can be found in "layout_api/impl" directory; they include:
--- * implementations with real system keyboard layout switching,
---   which use external platform-dependent libraries;
--- * an implementation switching 'iminsert' Vim option;
--- * mock implementation which operates on a local variable.
---
---@field default_layout LayoutID Default keyboard layout.
---@field get_layout fun(): LayoutID Get current keyboard layout.
---@field set_layout fun(layout: LayoutID) Set current system keyboard layout.

---@alias LayoutID any
---
---An opaque identifier of a keyboard layout. It is usually a string,
---but is allowed to be any type that can be compared (and be a key
---to a Lua table).
