---@class Schema
---
---A high-level SAKLS schema, which configures the SAKLS engine algorithm.
---
---@field memorized table<string, integer>
---@field forced table<string, integer>
---@field ignored table<string, boolean>
